require('plugins/packer')
require('plugins/treesitter')
require('plugins/lsp')
require('plugins/tokyo_night')
require('plugins/color_highlight')
require('plugins/cokeline')
require('plugins/feline')
require('plugins/neotree')
require('plugins/blackline')
require('plugins/autopairs')
require('plugins/toggleterm')

require('settings')
require('keymaps')
